### ISSUE TITLE
Wrong date on blog post: rustc_codegen_gcc: Progress Report #3

### ISSUE THREAD

**Issue by RagibHasin** [antoyo/jekyll-antoyo-blog#5]
Hi, your latest blog post [rustc_codegen_gcc: Progress Report #3](https://blog.antoyo.xyz/rustc_codegen_gcc-progress-report-3) has date from the previous progress report.

I think it should be 29 or 30 Aug 2021.

Cheers for your work on rustc_codegen_gcc.

**Comment by antoyo** [comment]
Thanks.
This seems fixed.
